fixed error

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,16 +40,16 @@ jobs:
       - name: Terraform Plan
         id: plan
         run: terraform plan -no-color -input=false -out tfplan
-        continue-on-error: true
+        continue-on-error: false
 
-      - name: Terraform Plan status
-         if steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform Plan status
+      #    if steps.plan.outcome == 'failure'
+      #   run: exit 1
 
-      # - name: Terraform Apply
-      #   id: apple
-      #   if: github.ref == "refs/heads/main" github.event_name == 'push'
-      #   run: terraform apply -no-color -input=false -auto-approve tfplan
+      - name: Terraform Apply
+        id: apple
+        if: github.ref == "refs/heads/main" github.event_name == 'push'
+        run: terraform apply -no-color -input=false -auto-approve tfplan
 
       # - name: Configure AWS credentials
       #   uses: aws-actions/configure-aws-credentials@v3
